-- Assign products to correct categories based on name keywords
-- Product categories: cat_milk, cat_fruit, cat_vegetable, cat_honey, cat_egg, cat_meat, cat_other

-- MILK products
UPDATE "products" SET "categoryId" = 'cat_milk'
WHERE LOWER(name) LIKE '%milk%'
   OR LOWER(name) LIKE '%cheese%'
   OR LOWER(name) LIKE '%yogurt%'
   OR LOWER(name) LIKE '%yoghurt%'
   OR LOWER(name) LIKE '%butter%'
   OR LOWER(name) LIKE '%cream%'
   OR LOWER(name) LIKE '%curd%'
   OR LOWER(name) LIKE '%quark%'
   OR LOWER(name) LIKE '%mozzarella%'
   OR LOWER(name) LIKE '%ricotta%'
   OR LOWER(name) LIKE '%camembert%'
   OR LOWER(name) LIKE '%raclette%'
   OR LOWER(name) LIKE '%fondue%'
   OR LOWER(name) LIKE '%käse%'
   OR LOWER(name) LIKE '%milch%';

-- FRUIT products
UPDATE "products" SET "categoryId" = 'cat_fruit'
WHERE LOWER(name) LIKE '%apple%'
   OR LOWER(name) LIKE '%apfel%'
   OR LOWER(name) LIKE '%pear%'
   OR LOWER(name) LIKE '%birne%'
   OR LOWER(name) LIKE '%cherry%'
   OR LOWER(name) LIKE '%kirsche%'
   OR LOWER(name) LIKE '%plum%'
   OR LOWER(name) LIKE '%pflaume%'
   OR LOWER(name) LIKE '%apricot%'
   OR LOWER(name) LIKE '%marille%'
   OR LOWER(name) LIKE '%peach%'
   OR LOWER(name) LIKE '%pfirsich%'
   OR LOWER(name) LIKE '%strawberry%'
   OR LOWER(name) LIKE '%erdbeer%'
   OR LOWER(name) LIKE '%raspberry%'
   OR LOWER(name) LIKE '%himbeer%'
   OR LOWER(name) LIKE '%blueberry%'
   OR LOWER(name) LIKE '%heidelbeer%'
   OR LOWER(name) LIKE '%blackberry%'
   OR LOWER(name) LIKE '%brombeer%'
   OR LOWER(name) LIKE '%grape%'
   OR LOWER(name) LIKE '%traube%'
   OR LOWER(name) LIKE '%currant%'
   OR LOWER(name) LIKE '%johannisbeer%'
   OR LOWER(name) LIKE '%gooseberry%'
   OR LOWER(name) LIKE '%stachelbeer%'
   OR LOWER(name) LIKE '%elderberry%'
   OR LOWER(name) LIKE '%holunder%'
   OR LOWER(name) LIKE '%berry%'
   OR LOWER(name) LIKE '%beere%'
   OR LOWER(name) LIKE '%fruit%'
   OR LOWER(name) LIKE '%obst%'
   OR LOWER(name) LIKE '%frucht%'
   OR LOWER(name) LIKE '%juice%'
   OR LOWER(name) LIKE '%saft%'
   OR LOWER(name) LIKE '%most%'
   OR LOWER(name) LIKE '%cider%'
   OR LOWER(name) LIKE '%compote%'
   OR LOWER(name) LIKE '%kompott%'
   OR LOWER(name) LIKE '%marmalade%'
   OR LOWER(name) LIKE '%jam%'
   OR LOWER(name) LIKE '%konfitüre%'
   OR LOWER(name) LIKE '%nuts%'
   OR LOWER(name) LIKE '%walnut%'
   OR LOWER(name) LIKE '%nuss%'
   OR LOWER(name) LIKE '%hazelnut%'
   OR LOWER(name) LIKE '%haselnuss%'
   OR LOWER(name) LIKE '%almond%'
   OR LOWER(name) LIKE '%mandel%'
   OR LOWER(name) LIKE '%chestnut%'
   OR LOWER(name) LIKE '%marone%'
   OR LOWER(name) LIKE '%quince%'
   OR LOWER(name) LIKE '%quitten%'
   OR LOWER(name) LIKE '%williams%'
   OR LOWER(name) LIKE '%kiwi%'
   OR LOWER(name) LIKE '%zitrone%'
   OR LOWER(name) LIKE '%dörrobst%'
   OR LOWER(name) LIKE 'dried fruit%'
   OR LOWER(name) LIKE '%zwetschge%';

-- VEGETABLE products
UPDATE "products" SET "categoryId" = 'cat_vegetable'
WHERE LOWER(name) LIKE '%salad%'
   OR LOWER(name) LIKE '%salat%'
   OR LOWER(name) LIKE '%lettuce%'
   OR LOWER(name) LIKE '%cabbage%'
   OR LOWER(name) LIKE '%kohl%'
   OR LOWER(name) LIKE '%carrot%'
   OR LOWER(name) LIKE '%rüebli%'
   OR LOWER(name) LIKE '%karotte%'
   OR LOWER(name) LIKE '%potato%'
   OR LOWER(name) LIKE '%kartoffel%'
   OR LOWER(name) LIKE '%tomato%'
   OR LOWER(name) LIKE '%tomate%'
   OR LOWER(name) LIKE '%cucumber%'
   OR LOWER(name) LIKE '%gurke%'
   OR LOWER(name) LIKE '%zucchini%'
   OR LOWER(name) LIKE '%onion%'
   OR LOWER(name) LIKE '%zwiebel%'
   OR LOWER(name) LIKE '%garlic%'
   OR LOWER(name) LIKE '%knoblauch%'
   OR LOWER(name) LIKE '%pumpkin%'
   OR LOWER(name) LIKE '%kürbis%'
   OR LOWER(name) LIKE '%squash%'
   OR LOWER(name) LIKE '%pepper%'
   OR LOWER(name) LIKE '%paprika%'
   OR LOWER(name) LIKE '%spinach%'
   OR LOWER(name) LIKE '%spinat%'
   OR LOWER(name) LIKE '%broccoli%'
   OR LOWER(name) LIKE '%cauliflower%'
   OR LOWER(name) LIKE '%blumenkohl%'
   OR LOWER(name) LIKE '%celery%'
   OR LOWER(name) LIKE '%sellerie%'
   OR LOWER(name) LIKE '%leek%'
   OR LOWER(name) LIKE '%lauch%'
   OR LOWER(name) LIKE '%asparagus%'
   OR LOWER(name) LIKE '%spargel%'
   OR LOWER(name) LIKE '%radish%'
   OR LOWER(name) LIKE '%rettich%'
   OR LOWER(name) LIKE '%beetroot%'
   OR LOWER(name) LIKE '%randen%'
   OR LOWER(name) LIKE '%rübe%'
   OR LOWER(name) LIKE '%bean%'
   OR LOWER(name) LIKE '%bohne%'
   OR LOWER(name) LIKE '%pea%'
   OR LOWER(name) LIKE '%erbse%'
   OR LOWER(name) LIKE '%lentil%'
   OR LOWER(name) LIKE '%linse%'
   OR LOWER(name) LIKE '%mushroom%'
   OR LOWER(name) LIKE '%pilz%'
   OR LOWER(name) LIKE '%champignon%'
   OR LOWER(name) LIKE '%herb%'
   OR LOWER(name) LIKE '%kraut%'
   OR LOWER(name) LIKE '%basil%'
   OR LOWER(name) LIKE '%basilikum%'
   OR LOWER(name) LIKE '%parsley%'
   OR LOWER(name) LIKE '%petersilie%'
   OR LOWER(name) LIKE '%chive%'
   OR LOWER(name) LIKE '%schnittlauch%'
   OR LOWER(name) LIKE '%rhubarb%'
   OR LOWER(name) LIKE '%rhabarber%'
   OR LOWER(name) LIKE '%corn%'
   OR LOWER(name) LIKE '%mais%'
   OR LOWER(name) LIKE '%artichoke%'
   OR LOWER(name) LIKE '%artischocke%'
   OR LOWER(name) LIKE '%eggplant%'
   OR LOWER(name) LIKE '%aubergine%'
   OR LOWER(name) LIKE '%vegetable%'
   OR LOWER(name) LIKE '%gemüse%'
   OR LOWER(name) LIKE '%gemuese%'
   OR LOWER(name) LIKE 'wild garlic%'
   OR LOWER(name) LIKE '%bärlauch%'
   OR LOWER(name) LIKE '%sauerkraut%'
   OR LOWER(name) LIKE '%chicory%'
   OR LOWER(name) LIKE '%chicorée%'
   OR LOWER(name) LIKE '%endive%'
   OR LOWER(name) LIKE '%batavia%'
   OR LOWER(name) LIKE '%lollo%'
   OR LOWER(name) LIKE '%rucola%'
   OR LOWER(name) LIKE '%ruccola%'
   OR LOWER(name) LIKE '%sugarloaf%'
   OR LOWER(name) LIKE '%zuckerhut%'
   OR LOWER(name) LIKE '%patisson%'
   OR LOWER(name) LIKE '%olive%'
   OR LOWER(name) LIKE '%parsnip%'
   OR LOWER(name) LIKE '%pastinake%';

-- HONEY products
UPDATE "products" SET "categoryId" = 'cat_honey'
WHERE LOWER(name) LIKE '%honey%'
   OR LOWER(name) LIKE '%honig%'
   OR LOWER(name) LIKE '%bee%'
   OR LOWER(name) LIKE '%biene%'
   OR LOWER(name) LIKE '%propolis%';

-- EGG products
UPDATE "products" SET "categoryId" = 'cat_egg'
WHERE LOWER(name) LIKE '%egg%'
   OR LOWER(name) LIKE '%ei%'
   OR LOWER(name) LIKE '%eier%';

-- MEAT products
UPDATE "products" SET "categoryId" = 'cat_meat'
WHERE LOWER(name) LIKE '%meat%'
   OR LOWER(name) LIKE '%fleisch%'
   OR LOWER(name) LIKE '%beef%'
   OR LOWER(name) LIKE '%rind%'
   OR LOWER(name) LIKE '%pork%'
   OR LOWER(name) LIKE '%schwein%'
   OR LOWER(name) LIKE '%chicken%'
   OR LOWER(name) LIKE '%huhn%'
   OR LOWER(name) LIKE '%hähnchen%'
   OR LOWER(name) LIKE '%turkey%'
   OR LOWER(name) LIKE '%pute%'
   OR LOWER(name) LIKE '%lamb%'
   OR LOWER(name) LIKE '%lamm%'
   OR LOWER(name) LIKE '%veal%'
   OR LOWER(name) LIKE '%kalb%'
   OR LOWER(name) LIKE '%sausage%'
   OR LOWER(name) LIKE '%wurst%'
   OR LOWER(name) LIKE '%ham%'
   OR LOWER(name) LIKE '%schinken%'
   OR LOWER(name) LIKE '%bacon%'
   OR LOWER(name) LIKE '%speck%'
   OR LOWER(name) LIKE '%venison%'
   OR LOWER(name) LIKE '%wild%'
   OR LOWER(name) LIKE '%hirsch%'
   OR LOWER(name) LIKE '%alpaca%'
   OR LOWER(name) LIKE '%buffalo%'
   OR LOWER(name) LIKE '%büffel%'
   OR LOWER(name) LIKE '%goose%'
   OR LOWER(name) LIKE '%gans%'
   OR LOWER(name) LIKE '%duck%'
   OR LOWER(name) LIKE '%ente%'
   OR LOWER(name) LIKE '%rabbit%'
   OR LOWER(name) LIKE '%kaninchen%'
   OR LOWER(name) LIKE '%horse%'
   OR LOWER(name) LIKE '%pferd%'
   OR LOWER(name) LIKE '%steak%'
   OR LOWER(name) LIKE '%bratwurst%'
   OR LOWER(name) LIKE '%cervelat%'
   OR LOWER(name) LIKE '%landjäger%'
   OR LOWER(name) LIKE '%jerky%'
   OR LOWER(name) LIKE '%trockenfleisch%'
   OR LOWER(name) LIKE '%bündnerfleisch%';