import { Farm } from '@swissfarm/types';

export const FARMS_DATA: Farm[] = [
  {
    id: '1',
    name: 'Hofmatt Bio Bauernhof',
    type: 'milk',
    products: ['milk', 'cheese', 'butter', 'yogurt'],
    location: { lat: 47.3769, lng: 8.5417 },
    address: 'Hofmattstrasse 12, 8001 Zürich',
    canton: 'ZH',
    website: 'https://hofmatt.ch',
    openingHours: 'Mon–Fri 07:00–18:00, Sat 07:00–16:00',
  },
  {
    id: '2',
    name: 'Berghof Selbstbedienung',
    type: 'self-service',
    products: ['eggs', 'vegetables', 'honey', 'jam'],
    location: { lat: 47.0502, lng: 8.3093 },
    address: 'Bergstrasse 45, 6003 Luzern',
    canton: 'LU',
    openingHours: '24/7 self-service',
  },
  {
    id: '3',
    name: 'Obstgarten Müller',
    type: 'pick-your-own',
    products: ['apples', 'cherries', 'strawberries', 'pears'],
    location: { lat: 47.5596, lng: 7.5886 },
    address: 'Obstweg 8, 4001 Basel',
    canton: 'BS',
    website: 'https://obstgarten-mueller.ch',
    openingHours: 'Jul–Oct: Daily 09:00–17:00',
  },
  {
    id: '4',
    name: 'Kinderbauernhof Sonnenschein',
    type: 'kids',
    products: ['educational tours', 'petting zoo', 'seasonal activities'],
    location: { lat: 46.948, lng: 7.4474 },
    address: 'Sonnenhang 3, 3001 Bern',
    canton: 'BE',
    website: 'https://kinderbauernhof-sonnenschein.ch',
    openingHours: 'Tue–Sun 10:00–17:00',
  },
  {
    id: '5',
    name: 'Alpage Gruyères',
    type: 'milk',
    products: ['gruyère cheese', 'milk', 'cream', 'butter'],
    location: { lat: 46.5858, lng: 7.0793 },
    address: 'Route de l\'Alpage 1, 1663 Gruyères',
    canton: 'FR',
    website: 'https://alpage-gruyeres.ch',
    openingHours: 'May–Oct: Daily 09:00–17:00',
  },
];
