import { Farm } from '@swissfarm/types';

export const FARMS_DATA: Farm[] = [
  {
    id: '1',
    name: 'Hofmatt Bio Bauernhof',
    type: 'milk',
    products: [
      { id: 'milk', name: 'milk' },
      { id: 'cheese', name: 'cheese' },
      { id: 'butter', name: 'butter' },
      { id: 'yogurt', name: 'yogurt' },
    ],
    location: { lat: 47.3769, lng: 8.5417 },
    address: 'Hofmattstrasse 12, 8001 Zürich',
    canton: 'ZH',
    website: 'https://hofmatt.ch',
    isActive: true,
    openingHours: [
      { day: 'monday', open: '07:00', close: '18:00' },
      { day: 'tuesday', open: '07:00', close: '18:00' },
      { day: 'wednesday', open: '07:00', close: '18:00' },
      { day: 'thursday', open: '07:00', close: '18:00' },
      { day: 'friday', open: '07:00', close: '18:00' },
      { day: 'saturday', open: '07:00', close: '16:00' },
    ],
  },
  {
    id: '2',
    name: 'Berghof Selbstbedienung',
    type: 'self_service',
    products: [
      { id: 'eggs', name: 'eggs' },
      { id: 'vegetables', name: 'vegetables' },
      { id: 'honey', name: 'honey' },
      { id: 'jam', name: 'jam' },
    ],
    location: { lat: 47.0502, lng: 8.3093 },
    address: 'Bergstrasse 45, 6003 Luzern',
    canton: 'LU',
    isActive: true,
    openingHours: [],
  },
  {
    id: '3',
    name: 'Obstgarten Müller',
    type: 'pick_your_own',
    products: [
      { id: 'apples', name: 'apples' },
      { id: 'cherries', name: 'cherries' },
      { id: 'strawberries', name: 'strawberries' },
      { id: 'pears', name: 'pears' },
    ],
    location: { lat: 47.5596, lng: 7.5886 },
    address: 'Obstweg 8, 4001 Basel',
    canton: 'BS',
    website: 'https://obstgarten-mueller.ch',
    isActive: true,
    openingHours: [
      { day: 'monday', open: '09:00', close: '17:00' },
      { day: 'tuesday', open: '09:00', close: '17:00' },
      { day: 'wednesday', open: '09:00', close: '17:00' },
      { day: 'thursday', open: '09:00', close: '17:00' },
      { day: 'friday', open: '09:00', close: '17:00' },
      { day: 'saturday', open: '09:00', close: '17:00' },
      { day: 'sunday', open: '09:00', close: '17:00' },
    ],
  },
  {
    id: '4',
    name: 'Kinderbauernhof Sonnenschein',
    type: 'kids',
    products: [
      { id: 'educational tours', name: 'educational tours' },
      { id: 'petting zoo', name: 'petting zoo' },
      { id: 'seasonal activities', name: 'seasonal activities' },
    ],
    location: { lat: 46.948, lng: 7.4474 },
    address: 'Sonnenhang 3, 3001 Bern',
    canton: 'BE',
    website: 'https://kinderbauernhof-sonnenschein.ch',
    isActive: true,
    openingHours: [
      { day: 'tuesday', open: '10:00', close: '17:00' },
      { day: 'wednesday', open: '10:00', close: '17:00' },
      { day: 'thursday', open: '10:00', close: '17:00' },
      { day: 'friday', open: '10:00', close: '17:00' },
      { day: 'saturday', open: '10:00', close: '17:00' },
      { day: 'sunday', open: '10:00', close: '17:00' },
    ],
  },
  {
    id: '5',
    name: 'Alpage Gruyères',
    type: 'milk',
    products: [
      { id: 'gruyère cheese', name: 'gruyère cheese' },
      { id: 'milk', name: 'milk' },
      { id: 'cream', name: 'cream' },
      { id: 'butter', name: 'butter' },
    ],
    location: { lat: 46.5858, lng: 7.0793 },
    address: "Route de l'Alpage 1, 1663 Gruyères",
    canton: 'FR',
    website: 'https://alpage-gruyeres.ch',
    isActive: true,
    openingHours: [
      { day: 'monday', open: '09:00', close: '17:00' },
      { day: 'tuesday', open: '09:00', close: '17:00' },
      { day: 'wednesday', open: '09:00', close: '17:00' },
      { day: 'thursday', open: '09:00', close: '17:00' },
      { day: 'friday', open: '09:00', close: '17:00' },
      { day: 'saturday', open: '09:00', close: '17:00' },
      { day: 'sunday', open: '09:00', close: '17:00' },
    ],
  },
];